config/routes.rb
Rails.application.routes.draw do

  root 'courses#index'


  get '/courses/data' => 'courses#data'

  resources :courses do
    resources :sheets
    resources :enrollments
  end

  get '/get_current_user_courses/:sheet_id',
    to: 'sheets#current_user_courses'
  post '/add_sheet_to_course/:course_id/:sheet_id',
    to: 'sheets#add_sheet_to_current_user_course'

  get '/sheets/scrape', to: 'sheets#scrape'

  resources :sheets do
    post 'favorites', to: 'favorites#create'
    delete 'favorites', to: 'favorites#destroy'
  end

  resources :users
  resources :charges

  get '/signup' => 'users#new'
  get '/users' => 'users#new'

  post '/fetch-element' => 'sheets#fetch'

  get '/login' => 'users#new'
  post '/login' => 'users#create'
  get '/logout' => 'users#logout'

end

app/models/sheet.rb
class Sheet < ActiveRecord::Base

  belongs_to :owner,  foreign_key: "user_id", class_name: 'User'

  has_many  :course_sheets
  has_many  :courses, through: :course_sheets, source: :course

  has_many :favorites
  has_many :users_favorited, through: :favorites, source: :user

  def video_tag
    self.video[/([^v=]*)$/]
  end

  def article_text
    scraper = Scraper::Client.new
    text = scraper.scrape(self.article)['content']
  end

end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :set_sheet, only: [:show, :edit, :update, :destroy]

  def index
    @sheets = Sheet.all
  end

  def show
    @appropriate_courses = []
    # if current_user
    #   courses = current_user.owned_courses
    #   p sheets
    #   p "*" * 100
    #   @appropriate_courses = Course.courses_without_sheet(courses, sheet)
    # end
    sheet = Sheet.find(params[:id])
  end

  def new
    @sheet = Sheet.new
    @course = Course.find(params[:course_id]) if params[:course_id]
  end

  def edit
  end

  def create
    @sheet = Sheet.new(sheet_params)

    @sheet.owner = current_user
    respond_to do |format|
      if @sheet.save
        CourseSheet.create!(course_id: params[:course_id], sheet_id: @sheet.id) if params[:course_id] != ""
        format.html { redirect_to @sheet, notice: 'Sheet was successfully created.' }
        format.json { render :show, status: :created, location: @sheet }
      else
        format.html { render :new }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  def fetch
    scraper = Scraper::Client.new
    content = scraper.scrape(params[:url])
    if content['error'] || content['excerpt'] == ""
      render plain: "Preview not currently available."
    else
      render html: scraper.scrape(params[:url])['content'][0,1000].html_safe
    end
  end

  def update
    respond_to do |format|
      if @sheet.update(sheet_params)
        format.html { redirect_to @sheet, notice: 'Sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @sheet }
      else
        format.html { render :edit }
        format.json { render json: @sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sheet.destroy
    respond_to do |format|
      format.html { redirect_to sheets_url, notice: 'Sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def scrape
    @sheet = Sheet.last
    render :scrape_test
  end

  def current_user_courses
    @sheet = Sheet.find(params[:sheet_id])
    courses = current_user.owned_courses
    @appropriate_courses = Course.courses_without_sheet(courses, @sheet)
    render partial: 'list_add_sheet_to_current_user_course'
  end

  def add_sheet_to_current_user_course
    course = Course.find(params[:course_id])
    course.sheets << Sheet.find(params[:sheet_id])
    render plain: "Sheet added!"
  end


  private
    def set_sheet
      @sheet = Sheet.find(params[:id])
    end

    def sheet_params
      params.require(:sheet).permit(:user_id, :article, :image, :video, :map, :title, :description)
    end
end

app/helpers/sheets_helper.rb
module SheetsHelper
  include Readability
  def self.parse_article(url)
    response = Readability.scrape(url)
    if response
      return response
    end
  end

end

app/views/sheets/_article_content.html.erb
<% if @sheet.article_text %>
  <p>
    <% sanitized_text = sanitize @sheet.article_text,
    tags: ['div', 'p'] %>
    <%= render html: sanitized_text.html_safe %>
  </p>
<% else %>
  <p>Sorry, article preview not currently available.
      Try viewing it <a href="<%= @sheet.article %>" target="_blank">remotely.</a>
  </p>
  <p>
    <%= link_to 'Edit', edit_sheet_path(@sheet) if @sheet.owner %>
  </p>
<% end %>

app/views/sheets/_emptyblock.html.erb
<div class="card medium">
  <% if @course.members.include?(current_user) %>
  <div class="card-image">
        <img src="http://www.colorhexa.com/10aded.png">
        <span class="card-title">Add A Sheet!</span>
      </div>
      <br/>
    <div class="row center-align">
      <%= link_to 'Create a sheet!', new_course_sheet_path(@course), :class => "btn" %><br>
      <% if @course.owner == current_user %>
        <br>
        <%= link_to 'Find a sheet', sheets_path, :class => "btn"  %>
      <% end %>
    </div>

  <% else %>
    <p>
      <em>Sheet pending...</em>
    </p>
  <% end %>
</div>

app/views/sheets/_favorite_button.html.erb
<%
button_path = "/sheets/#{@sheet.id}/favorites"
if current_user
  if current_user.favorited_sheets.include?(@sheet)
    button_text = "Unfavorite"
    button_class = "favorited favorite-button"
  else
    button_text = "Favorite this!"
    button_class = "favorite-button"
  end
end
%>

<button
  id="<%= button_path %>"
  class="<%= button_class %> btn blue darken-4 ">
  <%= button_text %>
</button>

app/views/sheets/_form.html.erb
<div class="new-sheet-area">
  <%= form_for([@course, @sheet]) do |f| %>
    <% if @sheet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@sheet.errors.count, "error") %> prohibited this sheet from being saved:</h2>

        <ul>
        <% @sheet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div id="form-submit">
      <div class="row">
       <div class="actions">
          <%= f.submit "Save Sheet", :class => "btn" %>
          <%= link_to 'Back',  url_for(:back), :class => "btn" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col s6">
        <div class="left-create">
          <div class="row">
            <div class="form-group">
              <%= f.label :title %><br>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <%= f.label :description %><br>
              <%= f.text_area :description, class: 'form-control' %>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <%= f.label :article_link %><br>
              <%= f.text_field :article, class: 'form-control' %>
              <div id="parsed" class="content"></div>
            </div>
          </div>
        </div>
      </div>


      <div class="col s6">
        <div class="right-create">
          <div class="row">
            <div class="form-group">
              <%= f.label :image %><br>
              <%= f.text_field :image, class: 'form-control' %>
              <img class="form-img" src="">
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <%= f.label :video %><br>
              <%= f.text_field :video, class: 'form-control' %>
              <iframe style="display: none" width="560" height="315" src="" frameborder="0" allowfullscreen></iframe>
            </div>
          </div>

          <div class="row">

            <div class="form-group">
              <%= f.label :map %><br>
              <%= f.text_field :map, class: 'form-control' %>
              <div id="sheet-map" data-location="<%= @sheet.map %>">
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/sheets/_link_add_sheet_to_course.html.erb
<%
# if current_user.owned_courses.any?
if @appropriate_courses.any?
  path = "/get_current_user_courses/#{@sheet.id}"
  text = "Add this sheet to a course!"
  link_class = "get-courses dropdown-button"
else
  path = "/courses/new"
  text = "Create a course!"
  link_class = ""
end
%>

<div class="get-courses">
  <!-- temp styling, obviously -->
  <a href="<%= path %>"
      class="<%= link_class %> btn" data-activates='dropdown1' >
    <%= text %>
  </a>
</div>


<ul id='dropdown1' class='dropdown-content'>

</ul>

app/views/sheets/_list_add_sheet_to_current_user_course.html.erb
<% if current_user %>
    <% if @appropriate_courses %>
        <% @appropriate_courses.each do |course| %>
          <li>
            <a href="/add_sheet_to_course/<%= course.id %>/<%= @sheet.id %>"
                class='add-sheet'>
              <%= course.title %>
            </a>
          </li>
        <% end %>
    <% end %>
<% end %>

app/views/sheets/_sheets_block.html.erb
  <div class="card medium">
    <div class="card-image">
      <img src="<%= sheet.image %>">
      <span class="card-title"><%= sheet.title %></span>
    </div>
    <div class="card-content">
      <p><%= sheet.description %></p>
      <div class="align-center">

      </div>
    </div>
    <div class="valign-wrapper">
      <a href="/sheets/<%= sheet.id %>" class="btn">View Sheet</a>
      <div class="valign">
        <% if @root %>
        <% else %>
          <% if sheet.owner %>
            <%= image_tag sheet.owner.gravatar_url, class: "circle responsive-img" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/sheets/edit.html.erb
<h1>Editing Sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sheet %> |
<%= link_to 'Back', sheets_path %>

app/views/sheets/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1 style="color: #000;">Listing Sheets</h1>

<div class="row">
  <% @sheets.each do |sheet| %>
    <div class="col s12 m3">
      <%= render partial: "sheets/sheets_block", locals: {sheet: sheet} %>
    </div>
  <% end %>
</div>

<%= link_to 'New Sheet', new_sheet_path, :class => "btn" %>
</div>

app/views/sheets/new.html.erb
<div id="create-sheet-head">
  <div class="container">
  <h1>Create a New Sheet!</h1>
  </div>
</div>

<div class="container">
<%= render 'form' %>
</div>

app/views/sheets/scrape_test.html.erb
<h5>
  <%= render html: @sheet.article_text.html_safe %>
  <%= @sheet.description %>
</h5>

app/views/sheets/show.html.erb
<div class="container">
  <div class="sheet-wrap">
    <div id="left">
      <div class="">
        <a class="waves-effect waves-light btn blue darken-4 facebook-share" href="<%= @sheet.id %>">Share this sheet!</a>
        <%= render partial: "favorite_button" %>
        <h1><%= @sheet.title %></h1>
      </div>
      <div class="sheet-text">



        <br>
        <%= render 'article_content' %>
        </div>
    </div>

      <div id="right">
        <div class="add-sheet-to-course right-align">
          <%= render 'link_add_sheet_to_course' %>
        </div>
            <div class="row">
              <div id="sheet-image">
                <div class="col s12 center-align">
                  <img class="responsive-img" src="<%= @sheet.image %>"/>
                </div>
              </div>
            </div>

            <div class="row">
              <div id="sheet-map" data-location="<%= @sheet.map %>">

              <div class="col s12">

                </div>
              </div>

              <div id="sheet-street-view" data-location="<%= @sheet.map %>">
                <div class="col s12">

                </div>
              </div>
            </div>

          <div class="row">
            <div id="sheet-video">
              <div class="col s12">
                <div class="video-container no-controls">
                  <iframe src="//www.youtube.com/embed/<%= @sheet.video_tag %>" frameborder="0" allowfullscreen></iframe>
                </div>
              </div>
            </div>
          </div>


        </div>
    </div>
  </div>
</div>