config/routes.rb
Rails.application.routes.draw do

  root 'courses#index'


  get '/courses/data' => 'courses#data'

  resources :courses do
    resources :sheets
    resources :enrollments
  end

  get '/get_current_user_courses/:sheet_id',
    to: 'sheets#current_user_courses'
  post '/add_sheet_to_course/:course_id/:sheet_id',
    to: 'sheets#add_sheet_to_current_user_course'

  get '/sheets/scrape', to: 'sheets#scrape'

  resources :sheets do
    post 'favorites', to: 'favorites#create'
    delete 'favorites', to: 'favorites#destroy'
  end

  resources :users
  resources :charges

  get '/signup' => 'users#new'
  get '/users' => 'users#new'

  post '/fetch-element' => 'sheets#fetch'

  get '/login' => 'users#new'
  post '/login' => 'users#create'
  get '/logout' => 'users#logout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cereal Box</title>
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//cdn.firebase.com/js/client/2.2.7/firebase.js"></script>

  <script src="//maps.googleapis.com/maps/api/js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
  <%= csrf_meta_tags %>

</head>
<body>


  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">CB</a>

        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li class="user-btn">
            <% if current_user %>
              <li><a href="/sheets">sheets</a></li>
              <li><a href="/users/<%= current_user.id%>"><%= current_user.username %> </a></li>
            <% else %>
              <li><a href="/sheets">sheets</a></li>
              <%= render partial: "users/modal" %>
            <% end %>
          </li>
          <% if current_user %>
            <li><a href="/logout">Log Out</a></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>

  <% if current_page?(root_url) || current_page?(courses_path) %>
  <div class="main-header">
    <div class="index">
      <div class="row">
        <div class="col-xs-12">
          <h1>Cereal Box</h1>
          <%= render partial: "indexbuttons" %>
        </div>
      </div>
    </div>
  </div>
  <% else %>
  <div class="page-wrap">

      <div class="page">
        <% end %>

        <%= yield %>
      </div>

  </div>


</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>